### ISSUE TITLE
aMaZiNg prOjeCt

### ISSUE THREAD

**Issue by Radhesh-Sarma** [Simran-Sahni/CodeforcesEngine#2]
SiNcE tHiS iS An aMaZiNg prOjeCt, lEts aDd reDmE for hecktoborfest pul reqest.

**Comment by amogh-saxena** [comment]
Cool Bhaiya

**Comment by amogh-saxena** [comment]
Helo this is amazing project, we need to put amazing project in title

**Comment by amogh-saxena** [comment]
you did an amazing job! do you mind if i clone your repository

**Comment by amogh-saxena** [comment]
Sorry if this is wrong spot to write this, but what you have made is absolutely jaw-dropping and an amazing piece of work!
